#! /bin/bash

# https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial

SCRIPT_NAME=$(basename $0)

helloWorld() {
    echo "Hello World!"
}

hi() {
    if [ -z "$1" ];then 
        echo 'Hi you!'
        exit
    fi

    echo "Hi ${1}!"
}

hiBob() {
    echo "Hi Bob!"
}

# Display the source code of this file
howItWorks() {
    cat $0
}

# List all functions that do not begin with an underscore _
_listAvailableFunctions() {
    cat $0 | grep -E '^[a-z]+[a-zA-Z0-9]*\(\) \{$' | sed 's#() {$##'
}

if [ $# -eq 0 ]; then
    _listAvailableFunctions
    exit
fi

$@
